name: flutter_drawable_mipmap
description: Flutter plugin that provides custom widget to show drawable and mipmap from android.
version: 1.1.0
homepage: https://github.com/sharmadhiraj/flutter_drawable_mipmap

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.sharmadhiraj.flutter_drawable_mipmap
        pluginClass: FlutterDrawableMipmapPlugin